### ISSUE TITLE
Element a[href="/cookies"] is not clickable or is not an in-page SPA navigation

### ISSUE THREAD

**Issue by fvilers** [nolanlawson/fuite#11]
Hi, while trying the tool with an Angular application, I get some errors about links that cannot be clicked.

Here's the error:
```
Test         : Go to /cookies and back
Failed       : Element a[href="/cookies"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
Error: Element a[href="/cookies"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/9228/node_modules/fuite/src/defaultScenario.js:35:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/9228/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/9228/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/9228/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/9228/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/9228/node_modules/fuite/src/index.js:184:17
```

Here's the link in the DOM: 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/1009621/146634271-88d5a34b-1d91-4657-80bb-fa3b95613c57.png">

**Comment by nolanlawson** [comment]
This is normal and can be ignored, unless it's affecting every link on the page. This just means that:

1. The default scenario tried to find all clickable internal links in the `createTests` step
2. But once it got to the `iteration` step, it turned out that not all of those links were truly clickable

This happens in situations such as if you have mixed MPA navigations and SPA navigations on the same page. Is there an error below the one you're seeing? That should tell you why it hit the error.

**Comment by fvilers** [comment]
This (and others) are real SPA links. I get other errors, but only the first two are related to links currently disabled because the application state currently disallow them (the user need to answer some questions first).

```
C:\Windows\system32>npx fuite https://123assur.be/courtiers/agifra-assurances/appart123/mon-appartement
Downloading Chromium r938248 - 174.1 Mb [====================] 100% 0.0s

URL       : https://123assur.be/courtiers/agifra-assurances/appart123/mon-appartement
Scenario  : Default
Iterations: 7 (Default)

TEST RESULTS

--------------------

Test         : Go to /courtiers/agifra-assurances/appart123/mes-donnees and back
Failed       : Element a[href="/courtiers/agifra-assurances/appart123/mes-donnees"] is not clickable or is not an in-page SPA navigation
element.click is not a function
TypeError: Element a[href="/courtiers/agifra-assurances/appart123/mes-donnees"] is not clickable or is not an in-page SPA navigation
element.click is not a function
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:35:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:106:9
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17
    at async runWithSpinner (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:59:13)

TypeError: element.click is not a function
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:33:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:106:9
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17
    at async runWithSpinner (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:59:13)
    at async runIteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:179:15)
    at async findLeaks (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:208:23)


--------------------

Test         : Go to /courtiers/agifra-assurances/appart123/confirmation and back
Failed       : Element a[href="/courtiers/agifra-assurances/appart123/confirmation"] is not clickable or is not an in-page SPA navigation
element.click is not a function
TypeError: Element a[href="/courtiers/agifra-assurances/appart123/confirmation"] is not clickable or is not an in-page SPA navigation
element.click is not a function
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:35:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:106:9
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17

TypeError: element.click is not a function
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:33:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:106:9
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17
    at async runWithSpinner (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:59:13)
    at async runIteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:179:15)


--------------------

Test         : Go to /courtiers/agifra-assurances/contact and back
Failed       : Element a[href="/courtiers/agifra-assurances/contact"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
Error: Element a[href="/courtiers/agifra-assurances/contact"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:35:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17

Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (C:\Users\Fabian\AppData\Roaming\npm-cache\_npx\20616\node_modules\fuite\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:343:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ElementHandle.click (C:\Users\Fabian\AppData\Roaming\npm-cache\_npx\20616\node_modules\fuite\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:416:26)
    at async clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:33:7)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17


--------------------

Test         : Go to /informations-legales and back
Failed       : Element a[href="/informations-legales"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
Error: Element a[href="/informations-legales"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:35:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17

Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (C:\Users\Fabian\AppData\Roaming\npm-cache\_npx\20616\node_modules\fuite\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:343:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ElementHandle.click (C:\Users\Fabian\AppData\Roaming\npm-cache\_npx\20616\node_modules\fuite\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:416:26)
    at async clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:33:7)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17


--------------------

Test         : Go to /cookies and back
Failed       : Element a[href="/cookies"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
Error: Element a[href="/cookies"] is not clickable or is not an in-page SPA navigation
Node is either not clickable or not an HTMLElement
    at clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:35:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17

Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (C:\Users\Fabian\AppData\Roaming\npm-cache\_npx\20616\node_modules\fuite\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:343:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ElementHandle.click (C:\Users\Fabian\AppData\Roaming\npm-cache\_npx\20616\node_modules\fuite\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:416:26)
    at async clickFirstVisible (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:33:7)
    at async iteration (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/defaultScenario.js:85:3)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:94:7
    at async runOnFreshPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:26:13)
    at async runIterationOnPage (file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:93:13)
    at async file:///C:/Users/Fabian/AppData/Roaming/npm-cache/_npx/20616/node_modules/fuite/src/index.js:184:17


--------------------
```

**Comment by nolanlawson** [comment]
Hmmm, `element.click` is not a function means that it couldn't find the element, probably because it already clicked it, pressed the back button, and then tried to click again. I assume in your app that, when you try to click the link but haven't answered any questions first, it will just do nothing? Do you call `event.preventDefault()` or something when the link is clicked in that case?

In any case,  it sounds like you need to run some setup code before analyzing the page. (E.g. to answer the questions.) You can define your own custom scenario with `--scenario`, or I'm working on a new flag to just add a setup function: #13

**Comment by fvilers** [comment]
OK, thanks, I'll go the scenario road.
