### ISSUE TITLE
Why doesn't it work on my website? Error about `element.click` not being a function

### ISSUE THREAD

**Issue by dumbmatter** [nolanlawson/fuite#113]
I have an SPA at https://play.basketball-gm.com/ and I tried running fuite on it with `npx run fuite https://play.basketball-gm.com/
` and it seems to not work with any of my links, it just shows stuff like this:

```
$ npx fuite https://play.basketball-gm.com/
Need to install the following packages:
fuite@5.0.0
Ok to proceed? (y) 


URL       : https://play.basketball-gm.com/
Scenario  : Default
Iterations: 7 (Default)

TEST RESULTS

--------------------

Test         : Go to /new_league and back
Failed       : Element a[href="/new_league"] is not clickable or is not an in-page SPA navigation 
element.click is not a function
TypeError: Element a[href="/new_league"] is not clickable or is not an in-page SPA navigation 
element.click is not a function
    at clickFirstVisible (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/defaultScenario.js:37:13)
    at async iteration (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/defaultScenario.js:90:3)
    at async file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:148:7
    at async runOnFreshPage (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:39:14)
    at async runIterationOnPage (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:147:13)
    at async file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:212:17
    at async runWithSpinner (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:81:13)
    at async runIteration (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:207:15)

TypeError: element.click is not a function
    at clickFirstVisible (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/defaultScenario.js:35:21)
    at async iteration (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/defaultScenario.js:90:3)
    at async file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:148:7
    at async runOnFreshPage (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:39:14)
    at async runIterationOnPage (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:147:13)
    at async file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:212:17
    at async runWithSpinner (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:81:13)
    at async runIteration (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:207:15)
    at async findLeaks (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:236:23)
    at async main (file:///home/jdscheff/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/cli.js:88:20)
```

...and similar errors for other pages it tries.

Maybe something about my router, which is custom rather than one of the common libraries. But the link in that error message is definitely clickable, and if I use the browser dev tools console to `.click()` it, it does load a new page at that new URL, like a normal SPA.

**Comment by nolanlawson** [comment]
It looks like occasionally it's getting stuck on this screen:

![Screenshot from 2024-08-22 19-23-39](https://github.com/user-attachments/assets/920691f7-48b1-4aab-b9d8-a513e9011446)

This screen doesn't have any elements that match the selector `a[href="/new_league"]` so it fails.

I think you'd need to make sure that the page loads the same thing every time. I'd also recommend trying `--debug` mode next time since it makes it a bit easier since you can see what the browser is doing.

Closing as this appears like a site issue.

**Comment by nolanlawson** [comment]
BTW thank you for `fake-indexeddb`! I am still using it to test [emoji-picker-element](https://github.com/nolanlawson/emoji-picker-element/). :slightly_smiling_face:

**Comment by dumbmatter** [comment]
Thanks, I'm seeing the same thing in debug mode.

This actually looks like a bug in Chrome related to using a shared workers in Chrome for Testing. Cause it's my shared worker that is not loading correctly, and if I go to chrome://inspect/#workers in a new tab and click "Inspect" it seems to load until I try to type something in the console, then it crashes after I type a couple characters. But if I switch to a normal worker, then actually fuite works fine.

So this is not your bug, but I guess in the rare case you're ever using a shared worker like this, you will not be surprised if it does weird stuff :)

I'm also now realizing that the README says this won't look for leaks in workers anyway, and that's where most of my logic is. Still might find something useful in my UI code though, we'll see!
