### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by davidjmstewart** [nolanlawson/fuite#119]
First time using this tool. I have a development server of a Vue app running on `localhost:1420`, so I ran `npx fuite http://localhost:1420` and received the following errors:

```
npx fuite http://localhost:1420
Need to install the following packages:
  fuite
Ok to proceed? (y) y

URL       : http://localhost:1420
Scenario  : Default
Iterations: 7 (Default)

TEST RESULTS

--------------------

Test         : Go to /colour-control and back
Failed       : Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at JSHeapSnapshot.calculateDiffForClass (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/thirdparty/devtools-frontend/index.js:3235:41)
    at JSHeapSnapshot.calculateSnapshotDiff (file:///C:/Users/David%2--------------------
Test         : Go to /colour-control and back
Failed       : Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at JSHeapSnapshot.calculateDiffForClass (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/thirdparty/devtools-frontend/index.js:3235:41)
    at JSHeapSnapshot.calculateSnapshotDiff (file:///C:/Users/David%2Test         : Go to /colour-control and back
Failed       : Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at JSHeapSnapshot.calculateDiffForClass (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/thirdparty/devtools-frontend/index.js:3235:41)
    at JSHeapSnapshot.calculateSnapshotDiff (file:///C:/Users/David%2Test         : Go to /colour-control and back
Failed       : Cannot read properties of undefined (reading 'name')
TypeError: Cannot read properties of undefined (reading 'name')
    at JSHeapSnapshot.calculateDiffForClass (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/thirdparty/devtools-frontend/index.js:3235:41)
    at JSHeapSnapshot.calculateSnapshotDiff (file:///C:/Users/David%2Test         : Go to /colour-control and back
Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/thirdparty/devtools-frontend/index.js:3208:31)
    at analyzeHeapSnapshots (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/metrics/heapsnapshots/analyzeHeapsnapshots.js:54:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getResult (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/metrics/heapsnapshots/index.js:19:66)
    at async serial (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/util.js:32:14)

    at async file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:193:25       
    at async runWithCdpSession (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:109:13)
    at async file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:149:15       
    at async runOnFreshPage (file:///C:/Users/David%20Stewart/AppData/Local/npm-cache/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:39:14)


--------------------
```

```
npx fuite --version
5.0.3
```

**Comment by nolanlawson** [comment]
The error is coming from [this line in devtools-frontend](https://github.com/ChromeDevTools/devtools-frontend/blob/e4d5c9170aa142560eabc1ee6f39629c5964dc8d/front_end/entrypoints/heap_snapshot_worker/HeapSnapshot.ts#L2483). This code seems to have changed a lot recently. Perhaps updating to the latest devtools-frontend would help.

Have you tested to see if this is a Windows-only error? Can you share a reproducible test?

**Comment by davidjmstewart** [comment]
> Please try v5.0.4, if that doesn't help see comment above.

Apologies for the radio silence. Just tried v5.0.4, and it worked without any issue :) I'll close the issue as it appears to be fixed now, thanks!
