### ISSUE TITLE
Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by melishev** [nolanlawson/fuite#23]
URL       : https://melishev.ru
Scenario  : Default
Iterations: 7 (Default)

TEST RESULTS

--------------------

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at Object.spawn (node:child_process:698:9)
    at BrowserRunner.start (/Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:91:34)
    at ChromeLauncher.launch (/Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:115:16)
    at async analyzeOptions (file:///Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:34:19)
    at async findLeaks (file:///Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:96:7)
    at async main (file:///Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/cli.js:87:20) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}

**Comment by nolanlawson** [comment]
I can't repro on my machine (running `fuite https://melishev.ru`). Can you confirm that [a Puppeteer hello world](https://pptr.dev) works?

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

**Comment by melishev** [comment]
@nolanlawson Most likely this is due to the fact that I have a Macbook M1

**Comment by nolanlawson** [comment]
Looks like you may be running into this error then? https://github.com/pa11y/pa11y/issues/619#issuecomment-986182745 There is a suggestion there for how to fix it.

**Comment by melishev** [comment]
```
URL       : https://melishev.com
Scenario  : Default
Iterations: 7 (Default)

TEST RESULTS

--------------------

Error: Tried to use PUPPETEER_EXECUTABLE_PATH env variable to launch browser but did not find any executable at: chromium not found
    at ChromeLauncher.launch (/Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:109:27)
    at async analyzeOptions (file:///Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:39:19)
    at async findLeaks (file:///Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/index.js:101:7)
    at async main (file:///Users/matvejmelishev/.npm/_npx/4f0bae50eb4a6363/node_modules/fuite/src/cli.js:87:20)
```

**Comment by nolanlawson** [comment]
Did you set a `PUPPETEER_EXECUTABLE_PATH` env var as described here? https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-787912758 Does it point to a valid Chromium installation?

**Comment by melishev** [comment]
yes

**Comment by nolanlawson** [comment]
I actually have access to an M1 Mac, so I tried the following:

1. Install latest stable NodeJS via the nodejs.org website (v16)
2. Run `npx fuite melishev.ru`

It worked fine; I did not see any errors. So I'm starting to suspect this is an environment issue with your setup?

**Comment by melishev** [comment]
This is very strange, did you follow the guides attached above, or does it work out of the box?
My Node.js version: 16.13.0

**Comment by melishev** [comment]
Could it be somehow related to the fact that I did not install Rozetta on my mac?

**Comment by nolanlawson** [comment]
I was using a MacBook Pro with a Pro (not Max) chip that didn't have any developer tools installed at all. (It was a releative's computer, not mine. :slightly_smiling_face:) I just installed NodeJS 16.13.1 from the website.

I don't recall changing any of the Rozetta settings or installing/uninstalling it.

**Comment by melishev** [comment]
@nolanlawson Well, I just ran a test for myself, and yes, it worked, thanks dude
