### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows

### ISSUE THREAD

**Issue by frederikhors** [nolanlawson/fuite#40]
I'm trying to launch this on my Windows 10 with:

`npx fuite http://localhost:4000 --setup .\setup.mjs`

or

`npx fuite http://localhost:4000 --setup ./setup.mjs`

but I get this error:

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at defaultResolve (node:internal/modules/esm/resolve:1016:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/esm/translators:111:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at main (file:///C:/prj/node_modules/fuite/src/cli.js:47:41)
    at file:///C:/prj/node_modules/fuite/src/cli.js:130:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

- setup.mjs:

```js
export async function setup(page) {
  await page.type("#email", "my@email.com");
  await page.type("#password", "pass");
  await page.click("submit");
}
```

Why?

**Comment by nolanlawson** [comment]
Looks like this line is the culprit:

https://github.com/nolanlawson/fuite/blob/7ec7aab48bda56e815dfbfc4dd1d91528d2275b3/src/cli.js#L47

I guess on Windows, this will become `c:\path\to\file`. I suppose I have to convert absolute filepaths to `file:` urls for Windows support.

**Comment by nolanlawson** [comment]
Should be fixed in 1.3.2.
