### ISSUE TITLE
error again v4.0.2 and During extra iteration for analysis: JavaScript heap out of memory

### ISSUE THREAD

**Issue by xqt-creator** [nolanlawson/fuite#89]
Hi,
similar to  https://github.com/nolanlawson/fuite/issues/86
despite upgrade to v4.0.2 ,I'm still getting this error。"ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory"

I have studied the latest merged code. https://github.com/nolanlawson/fuite/commit/b413f5b3801398e341b43592d2d337ef52f1b1a4

```
node --max-old-space-size=16000 ./node_modules/.bin/fuite   http://localhost:1234/tool --output ./out.json --setup ./mySetup.mjs -s ./myScenario.mjs

---


URL       : http://localhost:1234/tool
Scenario  : ./myScenario.mjs
Iterations: 7 (Default)
Output    : ./out.json

 TEST RESULTS
---------
⠦ Gathering tests...
<--- Last few GCs --->

[62300:0x118028000]   775347 ms: Scavenge 15786.9 (16024.1) -> 15786.7 (16035.6) MB, 18.8 / 0.0 ms  (average mu = 0.928, current mu = 0.733) allocation failure;
[62300:0x118028000]   775389 ms: Scavenge 15795.3 (16036.5) -> 15793.6 (16036.8) MB, 17.8 / 0.0 ms  (average mu = 0.928, current mu = 0.733) allocation failure;
[62300:0x118028000]   778900 ms: Scavenge 15795.5 (16036.8) -> 15793.4 (16058.3) MB, 3506.7 / 0.0 ms  (average mu = 0.928, current mu = 0.733) allocation failure;


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100cb3938 node::Abort() [v18.4.0/bin/node]
 2: 0x100cb3ac0 node::errors::TryCatchScope::~TryCatchScope() [v18.4.0/bin/node]
 3: 0x100e05944 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [v18.4.0/bin/node]
 4: 0x100fb0498 v8::internal::EmbedderStackStateScope::EmbedderStackStateScope(v8::internal::Heap*, v8::internal::EmbedderStackStateScope::Origin, cppgc::EmbedderStackState) [node/v18.4.0/bin/node]
 5: 0x100faef7c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [v18.4.0/bin/node]
 6: 0x100fa3224 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [v18.4.0/bin/node]
 7: 0x100fa3a54 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [v18.4.0/bin/node]
 8: 0x100f89888 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [v18.4.0/bin/node]
 9: 0x101319904 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [v18.4.0/bin/node]
10: 0x10166502c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [v18.4.0/bin/node]
11: 0x105fe8f18
12: 0x105fba9fc
13: 0x1016871c4 Builtins_ArrayReduceLoopContinuation [v18.4.0/bin/node]
14: 0x101687924 Builtins_ArrayReduce [v18.4.0/bin/node]
15: 0x105fea818
16: 0x105f997e0
17: 0x105f99248
18: 0x105f53e9c
...
[1]    62300 abort      node --max-old-space-size=16000  http://localhost:1234/tool
--output
```

I do have leaks in my app。
By annotating this function, I obtained the results in the table below. I suspect that the content of the "leak collections array" is too long, causing insufficient default JavaScript execution memory.

https://github.com/nolanlawson/fuite/blob/a004e33efe5a0f5e1d36d3bc2fa49c03990ab52a/src/index.js#L167-L178

```
Leaking collections:

╔════════╤════════╤═════════════════════════════════════╤═══════════════════╗
║ Type   │ Change │ Preview                             │ Size increased at ║
╟────────┼────────┼─────────────────────────────────────┼───────────────────╢
║ Array  │ +1     │ [{id, latency, entries}, ...]       │                   ║
╟────────┼────────┼─────────────────────────────────────┼───────────────────╢
║ Array  │ +301   │ [function init () {}, ...]              │               ║
╟────────┼────────┼─────────────────────────────────────┼───────────────────╢
║ Object │ +1     │ {1023: {id, latency, entries}, ...} │                   ║
╚════════╧════════╧═════════════════════════════════════╧═══════════════════╝
```

## One attempt

I attempted to modify the source code to analyze only the first 50 entries of the array, keeping the other parameters unchanged, and the program was able to run successfully.

```
return (await promisePool(PROMISE_POOL_SIZE, collections.map(collection => async () => {
    const res = { ...collection }
    if (collection.id in idsToStacktraces) {
      const stacktraces = idsToStacktraces[collection.id].slice(0,50)  // change
      if(idsToStacktraces[collection.id].length>50){      // change
        console.log('yes，you got it');                    // change
      }
      res.stacktraces = await Promise.all(stacktraces.map(async stacktrace => {
        return getStacktraceWithOriginalAndPretty(stacktrace)
      }))
    }
    return res
  })))
```

Can you give me some advice?

**Comment by nolanlawson** [comment]
Hmm, I wonder if we should just limit the `collections` array to some reasonable value. We only show the first 100 in the CLI, so arguably we should limit the `collections` array to 100 here.

However, I did want the CLI to indicate that the results were truncated, so we should probably report that somewhere in the returned JSON.

**Comment by nolanlawson** [comment]
How large is your `collections` array?

**Comment by xqt-creator** [comment]
> How large is your `collections` array?

Thank you for your reply。
I used the debug mode to get some intermediate running data, as shown below。

![image](https://github.com/nolanlawson/fuite/assets/11804672/0209735b-566f-40f6-9d22-7b292855e790)

The value of one of idsToStacktraces[0][0] items is:
```
idsToStacktraces[0][0] = 
    "Error\n    at obj.&lt;computed&gt; [as push] (pptr:evaluate;findLeakingCollections%20(file%3A%2F%2F%2FUsers%2Fsumeier%2Fworkspace%2Finspector%2Fnode_modules%2Ffuite%2Fsrc%2Fmetrics%2Fcollections%2Fcollections.js%3A112%3A41):93:30)\n    at createLoadableComponent (https://mms-sssssc.testtt.com/main/_next/static/chunks/pages/_app-ffeb6f00000fffff.js:109:7157)\n    at Loadable (https://mms-sssssc.testtt.com/main/_next/static/chunks/pages/_app-ffeb6f00000fffff.js:109:9097)\n    at MyLoadable (https://mms-sssssc.testtt.com/main/_next/static/chunks/pages/_app-ffeb6f00000fffff.js:41:3013)\n    at Loadable (https://mms-sssssc.testtt.com/main/_next/static/chunks/pages/_app-ffeb6f00000fffff.js:41:2452)\n    at https://mms-sssssc.testtt.com//tool/testte/js/main.b2c4789a.v20240125111337_eab9f030.js:2:1867803\n    at Array.map (&lt;anonymous&gt;)\n    at ie (mms-sssssc.testtt.com//tool/testte/js/main.b2c4789a.v20240125111337_eab9f030.js:2:1867757)\n    at of (https://funimg.pddpic.com/mms/react-dom-v18.2.0.min.js:109:301)\n    at Rk (https://invoke.testpng.blog/test/react-dom-v18.2.0.min.js:250:214)"

```

**Comment by nolanlawson** [comment]
What is the value of `collections.length` on line 320?

**Comment by xqt-creator** [comment]
> What is the value of `collections.length` on line 320?

collections.length = 3
![image](https://github.com/nolanlawson/fuite/assets/11804672/479cfaa6-2ebf-47bc-94df-f36805cee727)

**Comment by nolanlawson** [comment]
Bizarre. So it seems you have very few collections (3), but they are leaking lots of items (sizeBefore -> sizeAfter is 423 -> 2107).

**Comment by nolanlawson** [comment]
Please try v4.0.3. If that doesn't resolve your issue, then please provide a minimal repro.

**Comment by xqt-creator** [comment]
> Please try v4.0.3. If that doesn't resolve your issue, then please provide a minimal repro.


@nolanlawson Yes - this solves the problem, thank you for your patience in solving the issue.
